dist: trusty
sudo: required
osx_image: xcode10.1
# Not technically required but suppresses 'Ruby' in Job status message.
language: java
git:
  depth: 1
os:
  - linux
  - osx
env:
  - USE_BAZEL_VERSION=bazelbuild/3.2.0
  - USE_BAZEL_VERSION=bazelbuild/3.3.0
before_install:
  - npm install -g @bazel/bazelisk
  - cat .bazelrc.travis >> .bazelrc
script:
  - ./scripts/skylint.sh
  - ./test/run_all_tests.sh ci
  - ./scripts/gen-docs.sh && git diff --exit-code docs/
  - bazel shutdown
